config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
	root to:'blog/posts#index'
	
	namespace :authors do
		resources :posts
	end

	scope module: 'blog' do
		get 'about' => 'pages#about' ,  as: :about
		get 'contact' => 'pages#contact' ,  as: :contact
		get 'posts' =>'posts#index' ,  as: :posts
		get 'posts/:id' => 'posts#show' ,  as: :post
	end
	

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :posts


   def self.search(search)
	    where('title LIKE ?', "%#{search}%").order('id DESC')
	end
end

app/models/post.rb
class Post < ApplicationRecord
	extend FriendlyId
  		friendly_id :title, use: :slugged

      belongs_to :author , :optional => true
  	scope :most_recent, ->{order(id: :desc)}
  	validates :title, presence: true,uniqueness: true
  	validates :body, presence: true
  	def should_generate_new_friendly_id?
  		title_changed?
  	end

  	def day_published 
  		"Published On #{created_at.strftime('%-d %-b , %Y')}" 
  	end

  	def self.search(search)
	    where('title LIKE ?', "%#{search}%").order('id DESC')
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	layout 'author'
rescue_from ActionController::RoutingError do |exception|
 logger.error 'Routing error occurred'
 render plain: '404 Not found', status: 404 
end
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
	before_action :authenticate_author!
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy ]
    
    # GET /posts
    # GET /posts.json
   def index
    @posts = if params[:search]
        current_author.posts.search(params[:search])
      else
        current_author.posts.most_recent
      end
    end
    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = current_author.posts.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = current_author.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_posts_path, notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_posts_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Post was successfully deleted.' }
        format.json { head :no_content }
      end
    end


    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.friendly.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :body, :description , :banner_image_url )
      end

  end



end

app/controllers/blog/pages_controller.rb
module Blog
	class PagesController < BlogController
		def about
			
		end

		def contact
			
		end
	end
end

app/controllers/blog/posts_controller.rb
module Blog
  class PostsController < BlogController
    
    # GET /posts
    # GET /posts.json
   def index
      @posts = if params[:search]
        Post.search(params[:search])
      else
        Post.most_recent
      end
    end
    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = Post.friendly.find(params[:id])
    end

  end

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
	
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/posts/_form.html.erb
<%= form_for(post,url: url, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-lg-12">
    <div class="form-group">
      <div class="field">
        <%= form.label :title  %>
        <%= form.text_field :title , {:class => 'form-control'} %>
      </div>
    </div>
   
    <div class="form-group">
           <div class="field">
        <%= form.label :banner_image_url %>
        <%= form.text_field :banner_image_url ,{:class => 'form-control'}  %>
      </div>
    </div>
    <div class="form-group">
          <div class="field">
        <%= form.label :description %>
        <%= form.text_area :description , {:class => 'form-control'}  %>
      </div>
    </div>
     <div class="form-group">
       <div class="field">
        <%= form.label :body  %>
        <%= form.text_area :body , {:class => 'form-control'}  %>
      </div>
    </div>
    <div class="form-group">
      <div class="actions">
        <%= form.submit :Submit , {:class =>'btn btn-outline-primary '} %>
      </div>
    </div>
  </div>

 
<% end %>

app/views/authors/posts/_post.html.erb
<tr>
	<td width="60px">
		<img class="rounded" width="50px" height="50px" src="<%= post.banner_image_url %>" alt="Card image cap">
	</td>
	<td>
		<%= link_to post.title,authors_post_path(post) %>
	</td>
	<td>
		<%= truncate(post.description,length:100) %>
	</td>
	<td>
		<%= link_to 'Edit', edit_authors_post_path(post), class: 'btn btn-outline-primary ' %>
		<%= link_to 'Delete', authors_post_path(post),method: :delete, data:{confirm: 'Are you sure'}, class: 'btn btn-outline-danger ' %>
	</td>
</tr>	

app/views/authors/posts/edit.html.erb
<% provide(:page_title,"Edit #{@post.title}") %>

<% provide(:author, "active") %>
<div class="col text-right mb-3 mt-3">
	<%= link_to 'Back', authors_posts_path , class: 'btn btn-outline-secondary  ' %>
	<%= link_to 'Show Post', authors_post_path(@post) , class: 'btn btn-outline-secondary  ' %>
</div>
<h1>Editing Post</h1>


<%= render 'form', post: @post , url: authors_posts_url(@post) %>

app/views/authors/posts/index.html.erb
<% provide(:page_title,"All Post") %>
<% provide(:author, "active") %>
<% if notice %>
	<div class="alert alert-info mt-3 " role="alert">
		<%= notice %>
	</div>
<% end %>
<div class="row mt-3">
	<div class="col-lg-12 mt-3">
		<%= link_to 'Add New Post', new_authors_post_path() , class: 'btn btn-outline-success  ' %>
	</div>
	<div class="col-lg-12 mt-3">
		<table class="table table-bordered ">
			<thead class="table-dark">
				<tr>
					<th></th>
					<th>Title</th>
					<th>Description</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				 <%= render @posts %>
			</tbody>
		</table>
	</div>
	
 
</div>

app/views/authors/posts/new.html.erb
<% provide(:page_title,"New Post") %>
<% provide(:author, "active") %>

<div class="col text-right mb-3 mt-3">
	<%= link_to 'Back', authors_posts_path , class: 'btn btn-outline-secondary  ' %>
</div>

<h1>New Post</h1>

<%= render 'form', post: @post , url: authors_posts_url %>

app/views/authors/posts/show.html.erb
<% provide(:page_title,@post.title) %>
<% provide(:author, "active") %>
<% if notice %>
	<div class="alert alert-info mt-3 " role="alert">
		<%= notice %>
	</div>
<% end %>
<div class="col-lg-12 mb-3 mt-3 text-right">
	<%= link_to 'Add New Post',new_authors_post_path , class: 'btn btn-outline-success  ' %>
	<%= link_to 'Edit', edit_authors_post_path(@post), class: 'btn btn-outline-primary ' %>
	<%= link_to 'Delete', authors_post_path(@post),method: :delete, data:{confirm: 'Are you sure'}, class: 'btn btn-outline-danger ' %>
	<%= link_to 'Back', authors_posts_path , class: 'btn btn-outline-secondary ' %>
</div>
<div class="col-lg-12">
	  <div class="card bg-dark text-white">
	  	<img class="card-img" width="100%" height="350px" src="<%= @post.banner_image_url %>" alt="Card image">
		  <div class="card-img-overlay">
		    <h1 class="card-title text-center mt-5 align-middle"> <span> <%= @post.title %></span> </h1>
		    <h4 class="card-text desc  text-center  align-middle"><%= @post.description %></p>

		  </div>
	</div>
	  <div class="card-body">
	   
	    <p class="card-text"><%= @post.body.html_safe %></p>
	    
	  </div>
</div>

app/views/blog/pages/about.html.erb
<% provide(:about_active, "active") %>
<h1>About Us</h1>

app/views/blog/pages/contact.html.erb
<% provide(:contact_active, "active") %>

<h1>Contact Us</h1>

app/views/blog/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-lg-12">
    <div class="form-group">
      <div class="field">
        <%= form.label :title  %>
        <%= form.text_field :title , {:class => 'form-control'} %>
      </div>
    </div>
   
    <div class="form-group">
           <div class="field">
        <%= form.label :banner_image_url %>
        <%= form.text_field :banner_image_url ,{:class => 'form-control'}  %>
      </div>
    </div>
    <div class="form-group">
          <div class="field">
        <%= form.label :description %>
        <%= form.text_field :description , {:class => 'form-control'}  %>
      </div>
    </div>
     <div class="form-group">
       <div class="field">
        <%= form.label :body  %>
        <%= form.text_area :body , {:class => 'form-control'}  %>
      </div>
    </div>
    <div class="form-group">
      <div class="actions">
        <%= form.submit :Submit , {:class =>'btn btn-outline-primary '} %>
      </div>
    </div>
  </div>

 
<% end %>

app/views/blog/posts/_post.html.erb
<div class="col-md-4 mb-4">
  	<div class="card" style="min-height: 100%" >
	  <img class="card-img-top img-thumbnail" width="100%" height="250px" src="<%= post.banner_image_url %>" alt="Card image cap">
	  <div class="card-body">
	    <h5 class="card-title"><%= link_to post.title,post %></h5>
	    <p class="card-text"><%= truncate(post.description,length:130) %> </p>
	   	<%= link_to 'Read', post, class: 'btn btn-outline-primary ' %>
	    
	  </div>
		<div class="card-footer text-muted">
	    	<%= post.day_published  %>
	  	</div>
	</div>
</div>

app/views/blog/posts/edit.html.erb
<% provide(:blog_active, "active") %>
<div class="col text-right mb-3 mt-3">
	<%= link_to 'Back', posts_path , class: 'btn btn-outline-secondary  ' %>
</div>
<h1>Editing Post</h1>


<%= render 'form', post: @post %>

app/views/blog/posts/index.html.erb
<% provide(:page_title,"All Post") %>
<% provide(:blog_active, "active") %>

<div class="row mt-3">
  <%= render @posts %>
</div>

app/views/blog/posts/show.html.erb
<% provide(:page_title,@post.title) %>
<% provide(:blog_active, "active") %>
<% if notice %>
	<div class="alert alert-info mt-3 " role="alert">
		<%= notice %>
	</div>
<% end %>
<div class="col-lg-12 mb-3 mt-3 text-right">
	<%= link_to 'Back', posts_path , class: 'btn btn-outline-secondary ' %>
</div>
<div class="col-lg-12">
	  <div class="card bg-dark text-white">
	  	<img class="card-img" width="100%" height="350px" src="<%= @post.banner_image_url %>" alt="Card image">
		  <div class="card-img-overlay">
		    <h1 class="card-title text-center mt-5 align-middle"> <span> <%= @post.title %></span> </h1>
		    <h4 class="card-text desc  text-center  align-middle"><%= @post.description %></p>

		  </div>
	</div>
	  <div class="card-body">
	   
	    <p class="card-text"><%= @post.body %></p>
	    
	  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse"  id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item mr-2">
         <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
      </li>
      <li class="nav-item mr-2">
        <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
      </li>
      <li class="nav-item mr-2 ">
        <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
      </li>
      <% if author_signed_in?  %>
      <li class="nav-item mr-2 ">
        <%= link_to 'My Posts', authors_posts_path, class: "nav-link #{yield(:author)}" %>
      </li>
      <li class="nav-item mr-2 ">
        <%= link_to 'Logout', destroy_author_session_path, method: :delete ,  class: "nav-link" %>
      </li>
      <%= form_tag authors_posts_path, :method => 'get', :class => "form-inline my-2 my-lg-0" do %>
        <%= text_field_tag :search, params[:search] , {:class => 'form-control mr-sm-2'} %>
        <%= submit_tag "Search", :name => nil  , class: 'btn btn-outline-success my-2 my-sm-0'%>
      <% end %>
      <% else %>
        
        <li class="nav-item mr-2 ">
          <%= link_to 'Login', author_session_path,  class: "nav-link" %>
        </li>
        <%= form_tag posts_path, :method => 'get', :class => "form-inline my-2 my-lg-0" do %>
        <%= text_field_tag :search, params[:search] , {:class => 'form-control mr-sm-2'} %>
        <%= submit_tag "Search", :name => nil  , class: 'btn btn-outline-success my-2 my-sm-0'%>
      <% end %>

      <%  end %>
    </ul>
      
    
  </div>
</nav>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:page_title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=g6inan996gcaa2ogslqduua2xgcrj64wmweqlr14ipwxvyfz"></script>
  </head>

  <body>

    <%= render 'layouts/navbar' %>
    <% if notice %>
      <div class="alert alert-info mt-3 " role="alert" id="notice">
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-info mt-3 " role="alert" id="alert">
        <%= alert %>
      </div>
    <% end %>
    <div class="container <%= controller_name %> <%= action_name %> ">
    <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:page_title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container <%= controller_name %> <%= action_name %> ">
    <%= yield %>
    </div>
  </body>
</html>